//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F4.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Media {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Media() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F4.ConsoleApp.Media", typeof(Media).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark Twain
        ///Chewbarka
        ///Doc McDoggins
        ///Droolius Caesar
        ///Franz Fur-dinand
        ///Fyodor Dogstoevsky
        ///Hairy Paw-ter
        ///Jimmy Chew
        ///Kareem Abdul Ja-Bark
        ///Mary Puppins
        ///The Notorious D.O.G.
        ///Orville Redenbarker
        ///Ozzy Pawsborne
        ///Prince of Barkness
        ///Salvador Dogi
        ///Santa Paws
        ///Sarah Jessica Barker
        ///Sherlock Bones
        ///Winnie the Poodle
        ///Woofgang Puck
        ///Dobby
        ///Elmo
        ///Frodo
        ///Gollum
        ///Khaleesi
        ///Mister Miyagi
        ///Pikachu
        ///Pumba
        ///Rocky
        ///Yoda
        ///Archie
        ///Barney
        ///Betty
        ///Bernadette
        ///Bob
        ///Fergus
        ///Gary
        ///Kevin
        ///Larry
        ///Lloyd
        ///Matilda
        ///Olga
        ///Pam
        ///R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animal_names {
            get {
                return ResourceManager.GetString("animal_names", resourceCulture);
            }
        }
    }
}
